<?php echo '<?xml version="1.0" encoding="UTF-8" ?>'; ?>
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    {{-- Urls estaticas --}}
    <url>
        <loc>{{route('home.index')}}/</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>0.80</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/sobre-nosotros</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-de-familia/alimentos</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-de-familia/regimen-de-comunicacion-y-cuidado-personal</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-de-familia/divorcio</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-de-familia/violencia-familiar</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-de-familia/otros-reclamos-de-familia</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-laboral/despidos</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-laboral/accidentes-y-enfermedades-de-trabajo</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-penal</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-previsional</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/derecho-civil-y-comercial</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/contacto</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>0.80</priority>
      </url>
      <url>
        <loc>{{route('home.index')}}/blog</loc>
        <lastmod>2023-02-13T17:18:32+00:00</lastmod>
        <priority>1.00</priority>
      </url>
      
    @foreach ($posts as $post)
        <url>
            <loc>{{route('posts.show',$post)}}</loc>
            <lastmod>{{$post->updated_at->tz('UTC')->toAtomString()}}</lastmod>
            <priority>0.80</priority>
            <changefreq>daily</changefreq>
        </url>
    @endforeach
</urlset>